### PR TITLE
Refactor python streaming examples

### PR DESCRIPTION
**Pull request by IremErturk**

### CODE REVIEW

**Comment by IremErturk** [comment]
Hey Alexey, feel free to merge the pull request. I will create another one later to publish the solution

**Comment by alexeygrigorev** [comment]
It looks like there are some conflicts - Ankush added a README

**Comment by IremErturk** [comment]
Fix the merge conflicts, feel free to merge

**Comment by alexeygrigorev** [comment]
Thank you!

**Pull request merged**
