### PR TITLE
fix: avoid hardcoding schema info in dbt

### PR DESCRIPTION
**Pull request by anna-geller**

### CODE REVIEW

**Comment by alexeygrigorev** [comment]
Vic, can you please take a look?

**Comment by alexeygrigorev** [comment]
Also if we merge it, we should make a note somewhere explaining why it's different from the content of the video

**Comment by anna-geller** [comment]
if you feel more comfortable merging by keeping what was there before exactly, we can change those default values of env variables to be the ones that were hardcoded there:
```yaml
    database: "{{ env_var('DBT_DATABASE', 'taxi-rides-ny-339813-412521') }}"
    schema: "{{ env_var('DBT_SCHEMA', 'trips_data_all') }}"
```

**Comment by Victoriapm** [comment]
@anna-geller can you share some context on why is that you need that? Those schemas are the ones that are generated in the loading of the data (week 3), is that changing when including prefect?

**Review by Victoriapm — APPROVED** [review]
Other than understanding what changes, I see no concerns. 

Regarding clarification, with the defaults, it should only change what's shown for the BQ videos. But even in that case, if they change it to follow what the video shows, it would still work.

**Comment by anna-geller** [comment]
it's needed so that it works with any BigQuery schema from any user https://github.com/DataTalksClub/data-engineering-zoomcamp/blob/main/02-workflow-orchestration/flows/07_gcp_dbt.yaml#L25-L26 

As requested, I set the default to the one you used in the video :) Thx for getting this approved

@alexeygrigorev LMK if you need anything else

**Pull request merged**
