### PR TITLE
Adding aws Generate AWS access key README.

### PR DESCRIPTION
**Pull request by AnkushKhanna**

### CODE REVIEW

**Review by sejalv — APPROVED** [review]

**Comment by alexeygrigorev** [comment]
should we merge it?

**Comment by alexeygrigorev** [comment]
actually I'm not sure if we should put it to the main TF code - as it will require everyone on the course to have an AWS account. Perpahs we can make it a tutorial without changing the code?

**Comment by sejalv** [comment]
> actually I'm not sure if we should put it to the main TF code - as it will require everyone on the course to have an AWS account. Perpahs we can make it a tutorial without changing the code?

Hmm, that's true.

**Comment by butchkrohn** [comment]
Well do i start
 for awx

**Pull request closed without merging**
