### PR TITLE
Minor/trivial

### PR DESCRIPTION
**Pull request by mertse7en**

### CODE REVIEW

**Comment by alexeygrigorev** [comment]
Hi! Thank you for your PR! I'm hesitant to accept it because the video still has the old code version, so it can be confusing for some students if the code here is different from the code in the video.

**Comment by iamtodor** [comment]
@alexeygrigorev I would suggest adding some notes in the https://github.com/DataTalksClub/data-engineering-zoomcamp/blob/main/week_1_basics_n_setup/README.md file such as the code was updated to follow the best practices.
Because having strict versions in requirements it's a mandatory thing, right?

How does it look to you?

**Comment by iamtodor** [comment]
@alexeygrigorev I would suggest adding some notes in the https://github.com/DataTalksClub/data-engineering-zoomcamp/blob/main/week_1_basics_n_setup/README.md file such as the code was updated to follow the best practices.
Because having strict versions in requirements it's a mandatory thing, right?

Another point to consider `can be confusing for some students if the code here is different from the code in the video` imagine in just 3 months `SQLAlchemy` would be updated from `1.4.0` to `2.0.1` with a no back-ward compatibility. 
I would assume such a break will be much more confusing and harmful for the new students as the video will not be repeatable.

How does it look to you?

**Comment by alexeygrigorev** [comment]
Okay, indeed fixing versions makes sense. Would it be possible to do it without introducing the requirements.txt file? To minimize the changes

And adding a note to the README.md will be appreciated too

Thanks @iamtodor

**Comment by iamtodor** [comment]
@alexeygrigorev I'd suggest opening the issue to have better visibility of this improvement, in case @mertse7en cannot deliver your request within this PR

Because once you closed this PR the focus of this enhancement would be lost

**Pull request closed without merging**
