### PR TITLE
Update URL in homework 3

### PR DESCRIPTION
**Pull request by Wilson2214**
URL was incorrect leading to errors in downloading

### CODE REVIEW

**Comment by alexeygrigorev** [comment]
image
I get 404 when I try to open it

**Comment by alexeygrigorev** [comment]
Perhaps instead of replacing it, we should make one a clickable link, and mention the other as the prefix?

**Comment by Wilson2214** [comment]
I believe that is because the original is a link to view and download files, whereas my proposed URL is a true download link. If you add a filename at the end of the url like:

https://github.com/DataTalksClub/nyc-tlc-data/releases/download/green/green_tripdata_2019-01.csv.gz

you will trigger a download which I believe is required for ingesting the data.

**Comment by alexeygrigorev** [comment]
I think we can mention both?

**Comment by Wilson2214** [comment]
@alexeygrigorev see proposed update with both links

**Pull request merged**
